#!/usr/bin/env python3
"""
Interactive environment setup script for Inception.
Prompts for required environment variables and creates .env file.
"""

import os
import secrets
import getpass


def generate_secret_key():
    """Generate a secure random secret key."""
    return secrets.token_urlsafe(32)


def prompt_for_variable(name, description, required=True, default=None, secret=False):
    """Prompt user for an environment variable."""
    prompt = f"\n{name}\n{description}\n"
    if default:
        prompt += f"(Press Enter for default: {default})\n"
    prompt += "> "

    if secret:
        value = getpass.getpass(prompt)
    else:
        value = input(prompt).strip()

    if not value and default:
        return default

    if required and not value:
        print(f"Error: {name} is required!")
        return prompt_for_variable(name, description, required, default, secret)

    return value


def main():
    """Main setup function."""
    print("=" * 60)
    print("INCEPTION - Environment Setup")
    print("=" * 60)
    print("\nThis script will help you set up your environment variables.")
    print("All sensitive values will be stored in .env file.\n")

    env_vars = {}

    # Check if .env already exists
    env_path = os.path.join(os.path.dirname(__file__), '.env')
    if os.path.exists(env_path):
        response = input("\n.env file already exists. Overwrite? (y/N): ").strip().lower()
        if response != 'y':
            print("Setup cancelled.")
            return

    # Dashboard settings
    print("\n" + "=" * 60)
    print("DASHBOARD SETTINGS")
    print("=" * 60)

    env_vars['DASHBOARD_PASSWORD'] = prompt_for_variable(
        "DASHBOARD_PASSWORD",
        "Password for accessing the Inception web dashboard",
        required=True,
        secret=True
    )

    env_vars['SECRET_KEY'] = prompt_for_variable(
        "SECRET_KEY",
        "Secret key for Flask sessions (press Enter to auto-generate)",
        required=False,
        default=generate_secret_key(),
        secret=False
    )

    # AI API settings
    print("\n" + "=" * 60)
    print("AI API SETTINGS")
    print("=" * 60)

    env_vars['ANTHROPIC_API_KEY'] = prompt_for_variable(
        "ANTHROPIC_API_KEY",
        "Your Anthropic (Claude) API key (starts with sk-ant-api03-...)",
        required=True,
        secret=True
    )

    claude_oauth = prompt_for_variable(
        "CLAUDE_CODE_OAUTH_TOKEN",
        "Claude Code OAuth token (optional, press Enter to skip)",
        required=False,
        secret=True
    )
    if claude_oauth:
        env_vars['CLAUDE_CODE_OAUTH_TOKEN'] = claude_oauth

    # GitHub settings
    print("\n" + "=" * 60)
    print("GITHUB SETTINGS")
    print("=" * 60)

    env_vars['GITHUB_TOKEN'] = prompt_for_variable(
        "GITHUB_TOKEN",
        "GitHub personal access token for git operations (starts with ghp_...)",
        required=True,
        secret=True
    )

    # Render API settings
    print("\n" + "=" * 60)
    print("RENDER API SETTINGS")
    print("=" * 60)

    env_vars['RENDER_API_KEY'] = prompt_for_variable(
        "RENDER_API_KEY",
        "Render API key for managing deployments (starts with rnd_...)",
        required=True,
        secret=True
    )

    env_vars['RENDER_OWNER_ID'] = prompt_for_variable(
        "RENDER_OWNER_ID",
        "Your Render owner/team ID (starts with tea-... or usr-...)",
        required=True,
        secret=False
    )

    # Optional settings
    print("\n" + "=" * 60)
    print("OPTIONAL SETTINGS")
    print("=" * 60)

    data_dir = prompt_for_variable(
        "DATA_DIR",
        "Data directory for database (press Enter for current directory)",
        required=False,
        default=os.path.dirname(__file__),
        secret=False
    )
    if data_dir:
        env_vars['DATA_DIR'] = data_dir

    # Write .env file
    print("\n" + "=" * 60)
    print("WRITING .env FILE")
    print("=" * 60)

    with open(env_path, 'w') as f:
        f.write("# Inception Environment Variables\n")
        f.write("# Generated by setup_env.py\n")
        f.write("# DO NOT commit this file to git!\n\n")

        f.write("# Dashboard Settings\n")
        f.write(f"DASHBOARD_PASSWORD={env_vars['DASHBOARD_PASSWORD']}\n")
        f.write(f"SECRET_KEY={env_vars['SECRET_KEY']}\n\n")

        f.write("# AI API Settings\n")
        f.write(f"ANTHROPIC_API_KEY={env_vars['ANTHROPIC_API_KEY']}\n")
        if 'CLAUDE_CODE_OAUTH_TOKEN' in env_vars:
            f.write(f"CLAUDE_CODE_OAUTH_TOKEN={env_vars['CLAUDE_CODE_OAUTH_TOKEN']}\n")
        f.write("\n")

        f.write("# GitHub Settings\n")
        f.write(f"GITHUB_TOKEN={env_vars['GITHUB_TOKEN']}\n\n")

        f.write("# Render API Settings\n")
        f.write(f"RENDER_API_KEY={env_vars['RENDER_API_KEY']}\n")
        f.write(f"RENDER_OWNER_ID={env_vars['RENDER_OWNER_ID']}\n\n")

        if 'DATA_DIR' in env_vars:
            f.write("# Data Directory\n")
            f.write(f"DATA_DIR={env_vars['DATA_DIR']}\n\n")

    print(f"\n✓ Environment variables saved to {env_path}")
    print("\n" + "=" * 60)
    print("NEXT STEPS")
    print("=" * 60)
    print("\n1. Run the startup script:")
    print("   ./start_local.sh")
    print("\n2. Or manually:")
    print("   source .env")
    print("   python dashboard.py")
    print("\n" + "=" * 60)

    # Ask if user wants to sync to Render
    sync = input("\nSync these variables to Render services? (y/N): ").strip().lower()
    if sync == 'y':
        print("\nSyncing to Render...")
        try:
            import database
            import render_manager

            # Get all projects with Render service IDs
            db_path = os.path.join(os.path.dirname(__file__), 'inception.db')
            if os.path.exists(db_path):
                database.init_db()
                projects = database.get_all_projects()

                rm = render_manager.RenderManager(env_vars['RENDER_API_KEY'])

                for project in projects:
                    if project.get('render_service_id'):
                        print(f"\nSyncing to {project['name']} ({project['render_service_id']})...")

                        # Prepare env vars to sync
                        sync_vars = {
                            'ANTHROPIC_API_KEY': env_vars['ANTHROPIC_API_KEY'],
                            'GITHUB_TOKEN': env_vars['GITHUB_TOKEN'],
                            'DASHBOARD_PASSWORD': env_vars['DASHBOARD_PASSWORD'],
                            'SECRET_KEY': env_vars['SECRET_KEY'],
                        }

                        if 'CLAUDE_CODE_OAUTH_TOKEN' in env_vars:
                            sync_vars['CLAUDE_CODE_OAUTH_TOKEN'] = env_vars['CLAUDE_CODE_OAUTH_TOKEN']

                        success, result = rm.set_env_vars(project['render_service_id'], sync_vars)
                        if success:
                            print(f"  ✓ Synced to {project['name']}")
                        else:
                            print(f"  ✗ Failed to sync to {project['name']}: {result}")

                print("\n✓ Render sync complete!")
            else:
                print("Database not found. Skipping Render sync.")
        except Exception as e:
            print(f"\nError syncing to Render: {e}")
            print("You can sync manually later using the dashboard.")


if __name__ == '__main__':
    main()
